/**
 * Quiz Data - 8 quizzes per topic
 * Each quiz has:
 * - question: The quiz question
 * - options: 4 multiple choice options
 * - correct: Index of correct answer (0-3)
 * - explanation: Why the answer is correct
 */

export interface Quiz {
  id: string;
  question: string;
  options: string[];
  correct: number;
  explanation: string;
  difficulty: 'easy' | 'medium' | 'hard';
}

export interface TopicQuizzes {
  topicName: string;
  quizzes: Quiz[];
}

// All quizzes organized by topic
export const TOPIC_QUIZZES: Record<string, Quiz[]> = {
  // ==================== BASICS ====================

  'Variables & Types': [
    {
      id: 'vt-1',
      question: 'What is the correct way to create a variable in Python?',
      options: ['var x = 5', 'int x = 5', 'x = 5', 'let x = 5'],
      correct: 2,
      explanation: 'In Python, you simply assign a value to a variable name using =. No type declaration or keywords like var/let are needed.',
      difficulty: 'easy',
    },
    {
      id: 'vt-2',
      question: 'What is the data type of: x = 3.14?',
      options: ['int', 'float', 'double', 'decimal'],
      correct: 1,
      explanation: 'Numbers with decimal points are automatically typed as float in Python.',
      difficulty: 'easy',
    },
    {
      id: 'vt-3',
      question: 'Which function is used to check the type of a variable?',
      options: ['typeof()', 'type()', 'datatype()', 'gettype()'],
      correct: 1,
      explanation: 'The type() function returns the data type of any Python object.',
      difficulty: 'easy',
    },
    {
      id: 'vt-4',
      question: 'What will type(True) return?',
      options: ["<class 'bool'>", "<class 'int'>", "<class 'str'>", "<class 'boolean'>"],
      correct: 0,
      explanation: "True and False are boolean values in Python, so type() returns <class 'bool'>.",
      difficulty: 'medium',
    },
    {
      id: 'vt-5',
      question: 'Which is a valid variable name in Python?',
      options: ['2name', 'my-name', '_my_name', 'my name'],
      correct: 2,
      explanation: 'Variable names can start with letters or underscores, but not numbers. They cannot contain spaces or hyphens.',
      difficulty: 'medium',
    },
    {
      id: 'vt-6',
      question: 'What is the result of: int("42")?',
      options: ['Error', '"42"', '42', '42.0'],
      correct: 2,
      explanation: 'int() converts a string containing a number to an integer.',
      difficulty: 'medium',
    },
    {
      id: 'vt-7',
      question: 'What happens when you do: x = y = z = 10?',
      options: ['Syntax error', 'Only z gets 10', 'All three variables get 10', 'Only x gets 10'],
      correct: 2,
      explanation: 'Python allows multiple assignment in one line. All variables (x, y, z) will have the value 10.',
      difficulty: 'hard',
    },
    {
      id: 'vt-8',
      question: 'What is the output of: print(type(None))?',
      options: ["<class 'null'>", "<class 'None'>", "<class 'NoneType'>", "Error"],
      correct: 2,
      explanation: "None is Python's null value and its type is NoneType.",
      difficulty: 'hard',
    },
  ],

  'Operators': [
    {
      id: 'op-1',
      question: 'What is the result of: 10 // 3?',
      options: ['3.33', '3', '4', '3.0'],
      correct: 1,
      explanation: '// is the floor division operator. It divides and rounds down to the nearest integer.',
      difficulty: 'easy',
    },
    {
      id: 'op-2',
      question: 'What does the % operator do?',
      options: ['Division', 'Percentage', 'Modulo (remainder)', 'Power'],
      correct: 2,
      explanation: 'The % operator returns the remainder after division. For example, 10 % 3 = 1.',
      difficulty: 'easy',
    },
    {
      id: 'op-3',
      question: 'What is 2 ** 3 in Python?',
      options: ['6', '8', '5', '23'],
      correct: 1,
      explanation: '** is the exponentiation operator. 2 ** 3 means 2 to the power of 3 = 8.',
      difficulty: 'easy',
    },
    {
      id: 'op-4',
      question: 'What is the result of: 5 == 5.0?',
      options: ['True', 'False', 'Error', 'None'],
      correct: 0,
      explanation: 'Python compares the numeric values, not the types. 5 and 5.0 are equal in value.',
      difficulty: 'medium',
    },
    {
      id: 'op-5',
      question: 'What does "and" return in: True and False?',
      options: ['True', 'False', '1', '0'],
      correct: 1,
      explanation: 'The "and" operator returns True only if both operands are True.',
      difficulty: 'medium',
    },
    {
      id: 'op-6',
      question: 'What is the result of: not True?',
      options: ['True', 'False', 'None', 'Error'],
      correct: 1,
      explanation: 'The "not" operator inverts the boolean value. not True = False.',
      difficulty: 'medium',
    },
    {
      id: 'op-7',
      question: 'What does x += 5 mean?',
      options: ['x = 5', 'x = x + 5', 'x = x * 5', 'x + 5'],
      correct: 1,
      explanation: '+= is an augmented assignment operator. x += 5 is shorthand for x = x + 5.',
      difficulty: 'hard',
    },
    {
      id: 'op-8',
      question: 'What is the output of: print(10 > 5 > 2)?',
      options: ['True', 'False', 'Error', 'None'],
      correct: 0,
      explanation: 'Python supports chained comparisons. 10 > 5 > 2 means (10 > 5) and (5 > 2), which is True.',
      difficulty: 'hard',
    },
  ],

  'Input/Output': [
    {
      id: 'io-1',
      question: 'Which function is used to get user input?',
      options: ['get()', 'input()', 'read()', 'scan()'],
      correct: 1,
      explanation: 'The input() function reads a line from user input and returns it as a string.',
      difficulty: 'easy',
    },
    {
      id: 'io-2',
      question: 'What does input() always return?',
      options: ['integer', 'float', 'string', 'depends on input'],
      correct: 2,
      explanation: 'input() always returns a string, even if the user types a number.',
      difficulty: 'easy',
    },
    {
      id: 'io-3',
      question: 'How do you print without a newline at the end?',
      options: ['print(x, end="")', 'print(x, no_newline)', 'print(x, \\n)', 'println(x)'],
      correct: 0,
      explanation: 'The end parameter controls what is printed at the end. Default is "\\n" (newline).',
      difficulty: 'medium',
    },
    {
      id: 'io-4',
      question: 'What is the output of: print("A", "B", "C")?',
      options: ['ABC', 'A B C', 'A, B, C', 'Error'],
      correct: 1,
      explanation: 'print() separates multiple arguments with spaces by default.',
      difficulty: 'easy',
    },
    {
      id: 'io-5',
      question: 'How do you change the separator in print()?',
      options: ['print(a, b, separator="-")', 'print(a, b, sep="-")', 'print(a - b)', 'print(a, -, b)'],
      correct: 1,
      explanation: 'The sep parameter specifies the separator between print arguments.',
      difficulty: 'medium',
    },
    {
      id: 'io-6',
      question: 'What is an f-string in Python?',
      options: ['A file string', 'A formatted string literal', 'A function string', 'A float string'],
      correct: 1,
      explanation: 'F-strings (f"...") allow embedding expressions inside string literals using {expression}.',
      difficulty: 'medium',
    },
    {
      id: 'io-7',
      question: 'How do you get an integer from user input?',
      options: ['input(int)', 'int(input())', 'input().int()', 'integer(input())'],
      correct: 1,
      explanation: 'Wrap input() with int() to convert the string input to an integer.',
      difficulty: 'hard',
    },
    {
      id: 'io-8',
      question: 'What does print(f"{x:.2f}") do when x=3.14159?',
      options: ['Prints 3.14159', 'Prints 3.14', 'Prints 3', 'Error'],
      correct: 1,
      explanation: ':.2f formats a float with 2 decimal places.',
      difficulty: 'hard',
    },
  ],

  'Strings': [
    {
      id: 'str-1',
      question: 'How do you get the length of a string?',
      options: ['str.length', 'len(str)', 'str.size()', 'length(str)'],
      correct: 1,
      explanation: 'The len() function returns the number of characters in a string.',
      difficulty: 'easy',
    },
    {
      id: 'str-2',
      question: 'What is "Hello"[0]?',
      options: ['Hello', 'H', 'e', 'Error'],
      correct: 1,
      explanation: 'String indexing starts at 0, so [0] returns the first character.',
      difficulty: 'easy',
    },
    {
      id: 'str-3',
      question: 'What does "hello".upper() return?',
      options: ['hello', 'HELLO', 'Hello', 'Error'],
      correct: 1,
      explanation: 'The upper() method converts all characters to uppercase.',
      difficulty: 'easy',
    },
    {
      id: 'str-4',
      question: 'What is "Python"[-1]?',
      options: ['P', 'n', 'Error', 'Python'],
      correct: 1,
      explanation: 'Negative indexing starts from the end. -1 is the last character.',
      difficulty: 'medium',
    },
    {
      id: 'str-5',
      question: 'What does "a,b,c".split(",") return?',
      options: ['"a,b,c"', "['a', 'b', 'c']", '("a", "b", "c")', 'Error'],
      correct: 1,
      explanation: 'split() divides a string by the delimiter and returns a list.',
      difficulty: 'medium',
    },
    {
      id: 'str-6',
      question: 'How do you check if a string contains "test"?',
      options: ['str.contains("test")', '"test" in str', 'str.has("test")', 'str.find("test")'],
      correct: 1,
      explanation: 'The "in" operator checks if a substring exists in a string.',
      difficulty: 'medium',
    },
    {
      id: 'str-7',
      question: 'What is "Hello"[1:4]?',
      options: ['Hel', 'ell', 'ello', 'Hell'],
      correct: 1,
      explanation: 'Slicing [1:4] gets characters from index 1 up to (not including) index 4.',
      difficulty: 'hard',
    },
    {
      id: 'str-8',
      question: 'What does "  hello  ".strip() return?',
      options: ['"  hello  "', '"hello"', '"hello  "', '"  hello"'],
      correct: 1,
      explanation: 'strip() removes whitespace from both ends of a string.',
      difficulty: 'hard',
    },
  ],

  // ==================== CONTROL FLOW ====================

  'If Statements': [
    {
      id: 'if-1',
      question: 'What keyword is used for "otherwise if" in Python?',
      options: ['else if', 'elseif', 'elif', 'elsif'],
      correct: 2,
      explanation: 'Python uses "elif" as shorthand for "else if".',
      difficulty: 'easy',
    },
    {
      id: 'if-2',
      question: 'What must come at the end of an if statement line?',
      options: ['Semicolon ;', 'Colon :', 'Parentheses ()', 'Nothing'],
      correct: 1,
      explanation: 'Python if statements must end with a colon to indicate the start of the block.',
      difficulty: 'easy',
    },
    {
      id: 'if-3',
      question: 'Which comparison checks if x is NOT equal to y?',
      options: ['x <> y', 'x != y', 'x =! y', 'x not y'],
      correct: 1,
      explanation: '!= is the "not equal" comparison operator in Python.',
      difficulty: 'easy',
    },
    {
      id: 'if-4',
      question: 'What is the output of: print("Yes") if True else print("No")?',
      options: ['Yes', 'No', 'True', 'Error'],
      correct: 0,
      explanation: 'This is a ternary expression. Since the condition is True, "Yes" is printed.',
      difficulty: 'medium',
    },
    {
      id: 'if-5',
      question: 'How do you check if x is between 1 and 10 (inclusive)?',
      options: ['1 <= x <= 10', 'x >= 1 and x <= 10', 'Both A and B', 'x in range(1, 10)'],
      correct: 2,
      explanation: 'Both chained comparison (A) and logical and (B) work. Note: range(1,10) excludes 10.',
      difficulty: 'medium',
    },
    {
      id: 'if-6',
      question: 'What does an empty list evaluate to in a boolean context?',
      options: ['True', 'False', 'None', 'Error'],
      correct: 1,
      explanation: 'Empty sequences (list, string, tuple) are "falsy" and evaluate to False.',
      difficulty: 'medium',
    },
    {
      id: 'if-7',
      question: 'What is the result of: x = 5 if True else 10?',
      options: ['5', '10', 'True', 'Error'],
      correct: 0,
      explanation: 'Ternary expression: value_if_true if condition else value_if_false.',
      difficulty: 'hard',
    },
    {
      id: 'if-8',
      question: 'What happens if no condition is True and there is no else?',
      options: ['Error', 'Returns None', 'Nothing happens', 'Returns False'],
      correct: 2,
      explanation: 'If no conditions match and there is no else block, the program simply continues.',
      difficulty: 'hard',
    },
  ],

  'For Loops': [
    {
      id: 'for-1',
      question: 'What does range(5) produce?',
      options: ['1, 2, 3, 4, 5', '0, 1, 2, 3, 4', '0, 1, 2, 3, 4, 5', '1, 2, 3, 4'],
      correct: 1,
      explanation: 'range(5) produces numbers from 0 to 4 (5 numbers total, starting from 0).',
      difficulty: 'easy',
    },
    {
      id: 'for-2',
      question: 'How do you loop through items in a list called "fruits"?',
      options: ['for fruits in item:', 'for item in fruits:', 'foreach item in fruits:', 'for(item : fruits):'],
      correct: 1,
      explanation: 'The syntax is: for variable in iterable:',
      difficulty: 'easy',
    },
    {
      id: 'for-3',
      question: 'What does range(2, 5) produce?',
      options: ['2, 3, 4', '2, 3, 4, 5', '2, 5', '3, 4'],
      correct: 0,
      explanation: 'range(start, stop) produces numbers from start up to but not including stop.',
      difficulty: 'easy',
    },
    {
      id: 'for-4',
      question: 'How do you get both index and value when looping?',
      options: ['for i, v in list:', 'for i, v in enumerate(list):', 'for i, v in index(list):', 'for (i, v) = list:'],
      correct: 1,
      explanation: 'enumerate() returns both the index and value as tuples.',
      difficulty: 'medium',
    },
    {
      id: 'for-5',
      question: 'What does range(0, 10, 2) produce?',
      options: ['0, 2, 4, 6, 8', '0, 2, 4, 6, 8, 10', '2, 4, 6, 8', '0, 2'],
      correct: 0,
      explanation: 'range(start, stop, step) increments by step. This gives even numbers 0-8.',
      difficulty: 'medium',
    },
    {
      id: 'for-6',
      question: 'How do you iterate through a dictionary\'s keys and values?',
      options: ['for k, v in dict:', 'for k, v in dict.items():', 'for k, v in dict.pairs():', 'for (k, v) = dict:'],
      correct: 1,
      explanation: 'dict.items() returns key-value pairs as tuples.',
      difficulty: 'medium',
    },
    {
      id: 'for-7',
      question: 'What is: [x*2 for x in range(3)]?',
      options: ['[0, 1, 2]', '[0, 2, 4]', '[2, 4, 6]', '[1, 2, 3]'],
      correct: 1,
      explanation: 'This list comprehension doubles each value: 0*2, 1*2, 2*2 = [0, 2, 4].',
      difficulty: 'hard',
    },
    {
      id: 'for-8',
      question: 'What does the else block do in a for loop?',
      options: ['Runs if loop errors', 'Runs if break is called', 'Runs if loop completes normally', 'Not valid syntax'],
      correct: 2,
      explanation: 'The else block after a for loop runs only if the loop completes without hitting break.',
      difficulty: 'hard',
    },
  ],

  'While Loops': [
    {
      id: 'wh-1',
      question: 'When does a while loop stop?',
      options: ['After 10 iterations', 'When condition is False', 'When counter reaches 0', 'Never'],
      correct: 1,
      explanation: 'A while loop continues as long as its condition is True and stops when it becomes False.',
      difficulty: 'easy',
    },
    {
      id: 'wh-2',
      question: 'What creates an infinite loop?',
      options: ['while True:', 'while 1:', 'Both A and B', 'Neither'],
      correct: 2,
      explanation: 'Both while True: and while 1: create infinite loops (1 is truthy).',
      difficulty: 'easy',
    },
    {
      id: 'wh-3',
      question: 'How do you exit a while loop early?',
      options: ['exit', 'break', 'stop', 'return'],
      correct: 1,
      explanation: 'The break statement immediately exits the loop.',
      difficulty: 'easy',
    },
    {
      id: 'wh-4',
      question: 'What does continue do in a while loop?',
      options: ['Exits the loop', 'Skips to next iteration', 'Restarts the loop', 'Does nothing'],
      correct: 1,
      explanation: 'continue skips the rest of the current iteration and goes to the next one.',
      difficulty: 'medium',
    },
    {
      id: 'wh-5',
      question: 'How many times does this run: x=0; while x<3: x+=1?',
      options: ['2 times', '3 times', '4 times', 'Infinite'],
      correct: 1,
      explanation: 'x starts at 0, loops while x<3, incrementing each time. Runs for x=0,1,2 (3 times).',
      difficulty: 'medium',
    },
    {
      id: 'wh-6',
      question: 'What is wrong with: while x = 5:?',
      options: ['Nothing', '= should be ==', 'Missing colon', 'x not defined'],
      correct: 1,
      explanation: '= is assignment, == is comparison. Conditions need comparison operators.',
      difficulty: 'medium',
    },
    {
      id: 'wh-7',
      question: 'Can a while loop have an else clause?',
      options: ['No', 'Yes, runs if no break', 'Yes, runs if break', 'Yes, always runs'],
      correct: 1,
      explanation: 'Like for loops, while can have else that runs if loop ends without break.',
      difficulty: 'hard',
    },
    {
      id: 'wh-8',
      question: 'What is the output? x=5; while x: x-=1; print(x)',
      options: ['5', '0', '1', '-1'],
      correct: 1,
      explanation: 'Loop runs while x is truthy. When x becomes 0 (falsy), loop ends and prints 0.',
      difficulty: 'hard',
    },
  ],

  'Break & Continue': [
    {
      id: 'bc-1',
      question: 'What does break do?',
      options: ['Pauses the loop', 'Exits the loop', 'Skips iteration', 'Restarts loop'],
      correct: 1,
      explanation: 'break immediately terminates the loop and continues with code after the loop.',
      difficulty: 'easy',
    },
    {
      id: 'bc-2',
      question: 'What does continue do?',
      options: ['Exits loop', 'Skips to next iteration', 'Pauses loop', 'Ends program'],
      correct: 1,
      explanation: 'continue skips the remaining code in current iteration and starts the next one.',
      difficulty: 'easy',
    },
    {
      id: 'bc-3',
      question: 'Can break exit multiple nested loops at once?',
      options: ['Yes', 'No, only innermost', 'Only with flag', 'Depends on Python version'],
      correct: 1,
      explanation: 'break only exits the innermost loop. Use flags or functions to exit multiple loops.',
      difficulty: 'medium',
    },
    {
      id: 'bc-4',
      question: 'What prints? for i in range(5): if i==2: continue; print(i)',
      options: ['0 1 2 3 4', '0 1 3 4', '0 1', '2'],
      correct: 1,
      explanation: 'continue skips printing when i==2, so output is 0 1 3 4.',
      difficulty: 'medium',
    },
    {
      id: 'bc-5',
      question: 'What prints? for i in range(5): if i==2: break; print(i)',
      options: ['0 1 2 3 4', '0 1 3 4', '0 1', '2'],
      correct: 2,
      explanation: 'break exits when i==2, so only 0 and 1 are printed.',
      difficulty: 'medium',
    },
    {
      id: 'bc-6',
      question: 'Where can break and continue be used?',
      options: ['Anywhere', 'Only in loops', 'Only in functions', 'Only in if statements'],
      correct: 1,
      explanation: 'break and continue can only be used inside for or while loops.',
      difficulty: 'medium',
    },
    {
      id: 'bc-7',
      question: 'Does the else run? for i in range(3): if i==5: break; else: print("done")',
      options: ['Yes', 'No', 'Error', 'Sometimes'],
      correct: 0,
      explanation: 'break is never triggered (i never equals 5), so else runs.',
      difficulty: 'hard',
    },
    {
      id: 'bc-8',
      question: 'Does the else run? for i in range(3): if i==1: break; else: print("done")',
      options: ['Yes', 'No', 'Error', 'Sometimes'],
      correct: 1,
      explanation: 'break is triggered when i==1, so else does not run.',
      difficulty: 'hard',
    },
  ],

  // ==================== DATA STRUCTURES ====================

  'Lists': [
    {
      id: 'li-1',
      question: 'How do you create an empty list?',
      options: ['list = {}', 'list = []', 'list = ()', 'list = empty'],
      correct: 1,
      explanation: 'Square brackets [] create a list. {} creates a dictionary, () creates a tuple.',
      difficulty: 'easy',
    },
    {
      id: 'li-2',
      question: 'How do you add an item to the end of a list?',
      options: ['list.add(x)', 'list.append(x)', 'list.insert(x)', 'list.push(x)'],
      correct: 1,
      explanation: 'append() adds an item to the end of the list.',
      difficulty: 'easy',
    },
    {
      id: 'li-3',
      question: 'What is [1, 2, 3][1]?',
      options: ['1', '2', '3', 'Error'],
      correct: 1,
      explanation: 'Lists are zero-indexed. Index 1 is the second element, which is 2.',
      difficulty: 'easy',
    },
    {
      id: 'li-4',
      question: 'How do you remove an item by value?',
      options: ['list.delete(x)', 'list.remove(x)', 'list.pop(x)', 'del list[x]'],
      correct: 1,
      explanation: 'remove() deletes the first occurrence of the specified value.',
      difficulty: 'medium',
    },
    {
      id: 'li-5',
      question: 'What does list.pop() return?',
      options: ['Nothing', 'The removed item', 'The list length', 'True/False'],
      correct: 1,
      explanation: 'pop() removes and returns the last item (or item at specified index).',
      difficulty: 'medium',
    },
    {
      id: 'li-6',
      question: 'How do you sort a list in reverse order?',
      options: ['list.sort(reverse)', 'list.sort(reverse=True)', 'list.reverse().sort()', 'reverse(list.sort())'],
      correct: 1,
      explanation: 'sort() accepts a reverse parameter. reverse=True sorts in descending order.',
      difficulty: 'medium',
    },
    {
      id: 'li-7',
      question: 'What is [1, 2] + [3, 4]?',
      options: ['[1, 2, 3, 4]', '[4, 6]', '[[1,2], [3,4]]', 'Error'],
      correct: 0,
      explanation: 'The + operator concatenates lists.',
      difficulty: 'hard',
    },
    {
      id: 'li-8',
      question: 'What is [1, 2, 3][::-1]?',
      options: ['[1, 2, 3]', '[3, 2, 1]', '[1]', 'Error'],
      correct: 1,
      explanation: '[::-1] is a slice that reverses the list.',
      difficulty: 'hard',
    },
  ],

  'Tuples': [
    {
      id: 'tu-1',
      question: 'How do you create a tuple?',
      options: ['t = [1, 2]', 't = {1, 2}', 't = (1, 2)', 't = <1, 2>'],
      correct: 2,
      explanation: 'Tuples are created with parentheses ().',
      difficulty: 'easy',
    },
    {
      id: 'tu-2',
      question: 'What is the main difference between lists and tuples?',
      options: ['Tuples are faster', 'Tuples are immutable', 'Tuples can only hold numbers', 'No difference'],
      correct: 1,
      explanation: 'Tuples cannot be modified after creation (immutable), lists can (mutable).',
      difficulty: 'easy',
    },
    {
      id: 'tu-3',
      question: 'How do you create a tuple with one element?',
      options: ['(1)', '(1,)', '[1]', 'tuple(1)'],
      correct: 1,
      explanation: 'A single-element tuple needs a trailing comma: (1,). Without it, (1) is just 1.',
      difficulty: 'medium',
    },
    {
      id: 'tu-4',
      question: 'Can you use indexing on tuples?',
      options: ['No', 'Yes', 'Only positive indices', 'Only with tuple()'],
      correct: 1,
      explanation: 'Tuples support indexing and slicing just like lists.',
      difficulty: 'easy',
    },
    {
      id: 'tu-5',
      question: 'What happens when you try: t = (1, 2); t[0] = 5?',
      options: ['t becomes (5, 2)', 'Error', 't becomes [5, 2]', 'Nothing'],
      correct: 1,
      explanation: 'Tuples are immutable. Attempting to modify raises a TypeError.',
      difficulty: 'medium',
    },
    {
      id: 'tu-6',
      question: 'What is tuple unpacking?',
      options: ['Converting tuple to list', 'Assigning tuple elements to variables', 'Removing tuple elements', 'Joining tuples'],
      correct: 1,
      explanation: 'Unpacking assigns tuple elements to variables: a, b = (1, 2)',
      difficulty: 'medium',
    },
    {
      id: 'tu-7',
      question: 'Can tuples be dictionary keys?',
      options: ['No', 'Yes', 'Only if empty', 'Only numeric tuples'],
      correct: 1,
      explanation: 'Tuples are hashable (immutable), so they can be dictionary keys. Lists cannot.',
      difficulty: 'hard',
    },
    {
      id: 'tu-8',
      question: 'What does a, *b = (1, 2, 3, 4) assign to b?',
      options: ['2', '(2, 3, 4)', '[2, 3, 4]', 'Error'],
      correct: 2,
      explanation: 'The * operator collects remaining elements into a list: b = [2, 3, 4].',
      difficulty: 'hard',
    },
  ],

  'Dictionaries': [
    {
      id: 'di-1',
      question: 'How do you create an empty dictionary?',
      options: ['d = []', 'd = {}', 'd = ()', 'd = dict[]'],
      correct: 1,
      explanation: 'Curly braces {} create an empty dictionary.',
      difficulty: 'easy',
    },
    {
      id: 'di-2',
      question: 'How do you access a value by key?',
      options: ['dict.key', 'dict[key]', 'dict(key)', 'dict->key'],
      correct: 1,
      explanation: 'Use square brackets with the key: dict[key].',
      difficulty: 'easy',
    },
    {
      id: 'di-3',
      question: 'What happens if you access a non-existent key with dict[key]?',
      options: ['Returns None', 'Returns 0', 'KeyError', 'Returns empty string'],
      correct: 2,
      explanation: 'Accessing a missing key raises KeyError. Use .get() to avoid this.',
      difficulty: 'easy',
    },
    {
      id: 'di-4',
      question: 'What does dict.get("key", "default") return if key doesn\'t exist?',
      options: ['None', 'KeyError', '"default"', 'Empty string'],
      correct: 2,
      explanation: 'get() returns the default value if the key is not found.',
      difficulty: 'medium',
    },
    {
      id: 'di-5',
      question: 'How do you get all keys from a dictionary?',
      options: ['dict.keys', 'dict.keys()', 'keys(dict)', 'dict.getKeys()'],
      correct: 1,
      explanation: 'dict.keys() returns a view of all keys.',
      difficulty: 'medium',
    },
    {
      id: 'di-6',
      question: 'How do you check if a key exists in a dictionary?',
      options: ['dict.has(key)', 'dict.exists(key)', 'key in dict', 'dict.contains(key)'],
      correct: 2,
      explanation: 'The "in" operator checks if a key exists in a dictionary.',
      difficulty: 'medium',
    },
    {
      id: 'di-7',
      question: 'What does dict.items() return?',
      options: ['List of keys', 'List of values', 'List of (key, value) tuples', 'Dictionary copy'],
      correct: 2,
      explanation: 'items() returns a view of key-value pairs as tuples.',
      difficulty: 'hard',
    },
    {
      id: 'di-8',
      question: 'Can lists be dictionary keys?',
      options: ['Yes', 'No', 'Only empty lists', 'Only single-item lists'],
      correct: 1,
      explanation: 'Lists are mutable and unhashable, so they cannot be dictionary keys.',
      difficulty: 'hard',
    },
  ],

  'Sets': [
    {
      id: 'se-1',
      question: 'How do you create a set?',
      options: ['s = []', 's = {}', 's = {1, 2, 3}', 's = ()'],
      correct: 2,
      explanation: 'Sets use curly braces with values. Empty {} creates a dict, use set() for empty set.',
      difficulty: 'easy',
    },
    {
      id: 'se-2',
      question: 'What is special about set elements?',
      options: ['They are ordered', 'They are unique', 'They are strings', 'They are numbered'],
      correct: 1,
      explanation: 'Sets only contain unique elements. Duplicates are automatically removed.',
      difficulty: 'easy',
    },
    {
      id: 'se-3',
      question: 'How do you add an element to a set?',
      options: ['set.append(x)', 'set.add(x)', 'set.insert(x)', 'set.push(x)'],
      correct: 1,
      explanation: 'Sets use add() to add elements, not append().',
      difficulty: 'easy',
    },
    {
      id: 'se-4',
      question: 'What is {1, 2, 3} & {2, 3, 4}?',
      options: ['{1, 2, 3, 4}', '{2, 3}', '{1, 4}', 'Error'],
      correct: 1,
      explanation: '& is the intersection operator. It returns elements in both sets.',
      difficulty: 'medium',
    },
    {
      id: 'se-5',
      question: 'What is {1, 2, 3} | {2, 3, 4}?',
      options: ['{1, 2, 3, 4}', '{2, 3}', '{1, 4}', 'Error'],
      correct: 0,
      explanation: '| is the union operator. It returns all elements from both sets.',
      difficulty: 'medium',
    },
    {
      id: 'se-6',
      question: 'What is {1, 2, 3} - {2, 3, 4}?',
      options: ['{1, 2, 3, 4}', '{2, 3}', '{1}', '{4}'],
      correct: 2,
      explanation: '- is the difference operator. It returns elements in the first set but not the second.',
      difficulty: 'medium',
    },
    {
      id: 'se-7',
      question: 'Can sets contain lists?',
      options: ['Yes', 'No', 'Only empty lists', 'Only if converted'],
      correct: 1,
      explanation: 'Sets can only contain hashable (immutable) elements. Lists are mutable.',
      difficulty: 'hard',
    },
    {
      id: 'se-8',
      question: 'How do you create an empty set?',
      options: ['{}', 'set()', '[]', 'empty_set'],
      correct: 1,
      explanation: '{} creates an empty dictionary. Use set() for an empty set.',
      difficulty: 'hard',
    },
  ],

  'List Comprehensions': [
    {
      id: 'lc-1',
      question: 'What is [x for x in range(3)]?',
      options: ['[0, 1, 2]', '[1, 2, 3]', '[0, 1, 2, 3]', 'Error'],
      correct: 0,
      explanation: 'This comprehension creates a list of numbers from range(3): 0, 1, 2.',
      difficulty: 'easy',
    },
    {
      id: 'lc-2',
      question: 'What is [x*2 for x in [1, 2, 3]]?',
      options: ['[1, 2, 3]', '[2, 4, 6]', '[1, 4, 9]', '[3, 6, 9]'],
      correct: 1,
      explanation: 'Each element is multiplied by 2: 1*2, 2*2, 3*2 = [2, 4, 6].',
      difficulty: 'easy',
    },
    {
      id: 'lc-3',
      question: 'What is the basic syntax of a list comprehension?',
      options: ['[for x in list: expression]', '[expression for x in list]', 'list.map(expression)', '[x => expression]'],
      correct: 1,
      explanation: 'The syntax is [expression for item in iterable].',
      difficulty: 'easy',
    },
    {
      id: 'lc-4',
      question: 'What is [x for x in range(10) if x % 2 == 0]?',
      options: ['[0, 2, 4, 6, 8]', '[1, 3, 5, 7, 9]', '[2, 4, 6, 8, 10]', '[0, 2, 4, 6, 8, 10]'],
      correct: 0,
      explanation: 'The condition filters even numbers from 0-9.',
      difficulty: 'medium',
    },
    {
      id: 'lc-5',
      question: 'What is [x.upper() for x in ["a", "b"]]?',
      options: ["['a', 'b']", "['A', 'B']", "['A', 'b']", 'Error'],
      correct: 1,
      explanation: 'upper() is called on each string, converting to uppercase.',
      difficulty: 'medium',
    },
    {
      id: 'lc-6',
      question: 'Which is equivalent to list(map(str, [1,2,3]))?',
      options: ['[str(x) for x in [1,2,3]]', '[x.str() for x in [1,2,3]]', '[x for str in [1,2,3]]', '[(str)x for x in [1,2,3]]'],
      correct: 0,
      explanation: 'List comprehension [str(x) for x in list] is equivalent to map(str, list).',
      difficulty: 'medium',
    },
    {
      id: 'lc-7',
      question: 'What is [[j for j in range(3)] for i in range(2)]?',
      options: ['[[0,1,2], [0,1,2]]', '[[0,1], [0,1], [0,1]]', '[0,1,2,0,1,2]', 'Error'],
      correct: 0,
      explanation: 'This nested comprehension creates 2 lists, each containing [0, 1, 2].',
      difficulty: 'hard',
    },
    {
      id: 'lc-8',
      question: 'What is {x: x**2 for x in range(3)}?',
      options: ['{0, 1, 4}', '{0: 0, 1: 1, 2: 4}', '[0, 1, 4]', 'Error'],
      correct: 1,
      explanation: 'This is a dictionary comprehension. Keys are 0,1,2 and values are their squares.',
      difficulty: 'hard',
    },
  ],

  // ==================== FUNCTIONS ====================

  'Defining Functions': [
    {
      id: 'df-1',
      question: 'Which keyword is used to define a function?',
      options: ['function', 'func', 'def', 'define'],
      correct: 2,
      explanation: 'Python uses "def" to define functions.',
      difficulty: 'easy',
    },
    {
      id: 'df-2',
      question: 'What must come after a function definition line?',
      options: ['Semicolon', 'Colon', 'Parentheses', 'Nothing'],
      correct: 1,
      explanation: 'Function definitions end with a colon before the indented body.',
      difficulty: 'easy',
    },
    {
      id: 'df-3',
      question: 'How do you call a function named "greet"?',
      options: ['call greet', 'greet()', 'greet', 'run greet()'],
      correct: 1,
      explanation: 'Functions are called using their name followed by parentheses.',
      difficulty: 'easy',
    },
    {
      id: 'df-4',
      question: 'What is a docstring?',
      options: ['A comment', 'A string documenting the function', 'The function name', 'A return type'],
      correct: 1,
      explanation: 'A docstring is a string literal that documents what a function does.',
      difficulty: 'medium',
    },
    {
      id: 'df-5',
      question: 'Where do you put a docstring?',
      options: ['Before def', 'First line after def', 'Last line of function', 'After return'],
      correct: 1,
      explanation: 'Docstrings go as the first statement in the function body.',
      difficulty: 'medium',
    },
    {
      id: 'df-6',
      question: 'What does a function return if there is no return statement?',
      options: ['0', 'Empty string', 'None', 'Error'],
      correct: 2,
      explanation: 'Functions without a return statement implicitly return None.',
      difficulty: 'medium',
    },
    {
      id: 'df-7',
      question: 'Can a function be defined inside another function?',
      options: ['No', 'Yes', 'Only in classes', 'Only if named'],
      correct: 1,
      explanation: 'Python supports nested functions (functions defined inside other functions).',
      difficulty: 'hard',
    },
    {
      id: 'df-8',
      question: 'What is function.__name__ for: def greet(): pass?',
      options: ['"function"', '"greet"', 'None', 'Error'],
      correct: 1,
      explanation: '__name__ is a special attribute containing the function\'s name.',
      difficulty: 'hard',
    },
  ],

  'Return Values': [
    {
      id: 'rv-1',
      question: 'Which keyword returns a value from a function?',
      options: ['give', 'output', 'return', 'result'],
      correct: 2,
      explanation: 'The return keyword sends a value back from the function.',
      difficulty: 'easy',
    },
    {
      id: 'rv-2',
      question: 'Can a function return multiple values?',
      options: ['No', 'Yes, as a tuple', 'Only with special syntax', 'Only 2 values'],
      correct: 1,
      explanation: 'Functions can return multiple values, which are packed into a tuple.',
      difficulty: 'easy',
    },
    {
      id: 'rv-3',
      question: 'What happens after return executes?',
      options: ['Continues to next line', 'Function ends', 'Loops back', 'Error'],
      correct: 1,
      explanation: 'return immediately exits the function, returning control to the caller.',
      difficulty: 'easy',
    },
    {
      id: 'rv-4',
      question: 'What is: return a, b equivalent to?',
      options: ['return [a, b]', 'return {a, b}', 'return (a, b)', 'Syntax error'],
      correct: 2,
      explanation: 'Multiple return values are automatically packed into a tuple.',
      difficulty: 'medium',
    },
    {
      id: 'rv-5',
      question: 'How do you unpack multiple return values?',
      options: ['[a, b] = func()', 'a, b = func()', 'a & b = func()', '(a)(b) = func()'],
      correct: 1,
      explanation: 'Use tuple unpacking: a, b = func() where func returns two values.',
      difficulty: 'medium',
    },
    {
      id: 'rv-6',
      question: 'Can you have multiple return statements in one function?',
      options: ['No', 'Yes', 'Only in if/else', 'Only 2'],
      correct: 1,
      explanation: 'You can have multiple returns, but only one will execute per call.',
      difficulty: 'medium',
    },
    {
      id: 'rv-7',
      question: 'What does "return" with no value return?',
      options: ['0', '""', 'None', 'Error'],
      correct: 2,
      explanation: '"return" alone is equivalent to "return None".',
      difficulty: 'hard',
    },
    {
      id: 'rv-8',
      question: 'What is a generator function\'s return-like keyword?',
      options: ['generate', 'yield', 'give', 'produce'],
      correct: 1,
      explanation: 'yield produces values one at a time, making the function a generator.',
      difficulty: 'hard',
    },
  ],

  'Arguments': [
    {
      id: 'ar-1',
      question: 'What is a parameter?',
      options: ['Value passed to function', 'Variable in function definition', 'Return value', 'Function name'],
      correct: 1,
      explanation: 'Parameters are variables listed in the function definition.',
      difficulty: 'easy',
    },
    {
      id: 'ar-2',
      question: 'What is an argument?',
      options: ['Variable in definition', 'Value passed when calling', 'Function body', 'Return type'],
      correct: 1,
      explanation: 'Arguments are actual values passed to the function when calling it.',
      difficulty: 'easy',
    },
    {
      id: 'ar-3',
      question: 'How do you define a default parameter value?',
      options: ['def f(x=5):', 'def f(x:5):', 'def f(x==5):', 'def f(x->5):'],
      correct: 0,
      explanation: 'Default values use = in the parameter: def f(x=5):',
      difficulty: 'easy',
    },
    {
      id: 'ar-4',
      question: 'What is a keyword argument?',
      options: ['Any argument', 'Argument with name specified', 'First argument', 'Last argument'],
      correct: 1,
      explanation: 'Keyword arguments specify the parameter name: func(name="value").',
      difficulty: 'medium',
    },
    {
      id: 'ar-5',
      question: 'What does *args do?',
      options: ['Required arguments', 'Collects extra positional args', 'Keyword args only', 'No arguments'],
      correct: 1,
      explanation: '*args collects additional positional arguments into a tuple.',
      difficulty: 'medium',
    },
    {
      id: 'ar-6',
      question: 'What does **kwargs do?',
      options: ['Collects positional args', 'Collects keyword args', 'Double arguments', 'Error'],
      correct: 1,
      explanation: '**kwargs collects additional keyword arguments into a dictionary.',
      difficulty: 'medium',
    },
    {
      id: 'ar-7',
      question: 'What is wrong with: def f(a=1, b):?',
      options: ['Nothing', 'Default before non-default', 'Missing colon', 'Too many params'],
      correct: 1,
      explanation: 'Non-default parameters cannot follow default parameters.',
      difficulty: 'hard',
    },
    {
      id: 'ar-8',
      question: 'In def f(a, *args, b), what is b?',
      options: ['Positional arg', 'Keyword-only arg', 'Default arg', 'Error'],
      correct: 1,
      explanation: 'Parameters after *args must be passed as keyword arguments.',
      difficulty: 'hard',
    },
  ],

  'Lambda Functions': [
    {
      id: 'la-1',
      question: 'What is a lambda function?',
      options: ['Named function', 'Anonymous function', 'Class method', 'Built-in function'],
      correct: 1,
      explanation: 'Lambda functions are small anonymous functions without a name.',
      difficulty: 'easy',
    },
    {
      id: 'la-2',
      question: 'What is the syntax for a lambda that doubles x?',
      options: ['lambda x: x*2', 'lambda(x) x*2', 'def lambda x: x*2', 'x => x*2'],
      correct: 0,
      explanation: 'Lambda syntax: lambda parameters: expression',
      difficulty: 'easy',
    },
    {
      id: 'la-3',
      question: 'Can lambdas have multiple statements?',
      options: ['Yes', 'No', 'Only 2', 'With semicolons'],
      correct: 1,
      explanation: 'Lambdas can only contain a single expression, not statements.',
      difficulty: 'medium',
    },
    {
      id: 'la-4',
      question: 'What is (lambda x, y: x + y)(3, 4)?',
      options: ['7', 'lambda x, y: x + y', 'Error', 'None'],
      correct: 0,
      explanation: 'The lambda is immediately called with args 3, 4. Result: 3 + 4 = 7.',
      difficulty: 'medium',
    },
    {
      id: 'la-5',
      question: 'Which is often used with lambda?',
      options: ['print()', 'input()', 'map(), filter()', 'open()'],
      correct: 2,
      explanation: 'map() and filter() commonly use lambda for quick transformations.',
      difficulty: 'medium',
    },
    {
      id: 'la-6',
      question: 'What is list(map(lambda x: x**2, [1,2,3]))?',
      options: ['[1, 2, 3]', '[1, 4, 9]', '[2, 4, 6]', 'Error'],
      correct: 1,
      explanation: 'Lambda squares each element: 1²=1, 2²=4, 3²=9.',
      difficulty: 'medium',
    },
    {
      id: 'la-7',
      question: 'What is list(filter(lambda x: x>2, [1,2,3,4]))?',
      options: ['[1, 2]', '[3, 4]', '[1, 2, 3, 4]', '[]'],
      correct: 1,
      explanation: 'filter keeps elements where lambda returns True (x > 2).',
      difficulty: 'hard',
    },
    {
      id: 'la-8',
      question: 'How do you sort by second element: [(1,2), (3,1)]?',
      options: ['sorted(list, key=lambda x: x[0])', 'sorted(list, key=lambda x: x[1])', 'sorted(list, reverse=True)', 'list.sort(1)'],
      correct: 1,
      explanation: 'key=lambda x: x[1] sorts by the second element (index 1).',
      difficulty: 'hard',
    },
  ],

  'Scope': [
    {
      id: 'sc-1',
      question: 'What is local scope?',
      options: ['Global variables', 'Variables inside a function', 'Class variables', 'Module variables'],
      correct: 1,
      explanation: 'Local scope refers to variables defined inside a function.',
      difficulty: 'easy',
    },
    {
      id: 'sc-2',
      question: 'What is global scope?',
      options: ['Inside functions', 'Outside all functions', 'Inside classes', 'Inside loops'],
      correct: 1,
      explanation: 'Global scope is at the module level, outside all functions.',
      difficulty: 'easy',
    },
    {
      id: 'sc-3',
      question: 'How do you modify a global variable inside a function?',
      options: ['Just assign it', 'Use global keyword', 'Use local keyword', 'Cannot modify'],
      correct: 1,
      explanation: 'Use "global varname" to modify a global variable inside a function.',
      difficulty: 'medium',
    },
    {
      id: 'sc-4',
      question: 'What is LEGB rule?',
      options: ['Error types', 'Scope resolution order', 'Variable types', 'Function types'],
      correct: 1,
      explanation: 'LEGB: Local, Enclosing, Global, Built-in - the order Python searches for names.',
      difficulty: 'medium',
    },
    {
      id: 'sc-5',
      question: 'What is enclosing scope?',
      options: ['Global scope', 'Local scope', 'Outer function scope', 'Class scope'],
      correct: 2,
      explanation: 'Enclosing scope is the scope of an outer (enclosing) function.',
      difficulty: 'medium',
    },
    {
      id: 'sc-6',
      question: 'What keyword accesses enclosing scope?',
      options: ['global', 'nonlocal', 'outer', 'enclosing'],
      correct: 1,
      explanation: 'nonlocal is used to modify variables in an enclosing function scope.',
      difficulty: 'hard',
    },
    {
      id: 'sc-7',
      question: 'What happens: x=1; def f(): x=2; f(); print(x)?',
      options: ['Prints 1', 'Prints 2', 'Error', 'Prints None'],
      correct: 0,
      explanation: 'x=2 inside f() creates a local variable. Global x remains 1.',
      difficulty: 'hard',
    },
    {
      id: 'sc-8',
      question: 'What happens: x=1; def f(): global x; x=2; f(); print(x)?',
      options: ['Prints 1', 'Prints 2', 'Error', 'Prints None'],
      correct: 1,
      explanation: '"global x" makes x refer to the global variable, which is changed to 2.',
      difficulty: 'hard',
    },
  ],

  // ==================== OOP ====================

  'Classes': [
    {
      id: 'cl-1',
      question: 'Which keyword defines a class?',
      options: ['def', 'class', 'struct', 'object'],
      correct: 1,
      explanation: 'The "class" keyword is used to define a class in Python.',
      difficulty: 'easy',
    },
    {
      id: 'cl-2',
      question: 'What is __init__?',
      options: ['Destructor', 'Constructor', 'Iterator', 'Generator'],
      correct: 1,
      explanation: '__init__ is the constructor method, called when creating an instance.',
      difficulty: 'easy',
    },
    {
      id: 'cl-3',
      question: 'What is the first parameter of instance methods?',
      options: ['this', 'self', 'me', 'instance'],
      correct: 1,
      explanation: 'By convention, "self" refers to the instance in method definitions.',
      difficulty: 'easy',
    },
    {
      id: 'cl-4',
      question: 'How do you create an instance of class Dog?',
      options: ['new Dog()', 'Dog.new()', 'Dog()', 'create Dog()'],
      correct: 2,
      explanation: 'Call the class name like a function: Dog()',
      difficulty: 'medium',
    },
    {
      id: 'cl-5',
      question: 'What is an instance attribute?',
      options: ['Shared by all instances', 'Unique to each instance', 'Method', 'Class name'],
      correct: 1,
      explanation: 'Instance attributes are unique to each object, usually set in __init__.',
      difficulty: 'medium',
    },
    {
      id: 'cl-6',
      question: 'What is a class attribute?',
      options: ['Unique to instance', 'Shared by all instances', 'Private variable', 'Method'],
      correct: 1,
      explanation: 'Class attributes are shared by all instances of the class.',
      difficulty: 'medium',
    },
    {
      id: 'cl-7',
      question: 'What does __str__ do?',
      options: ['Converts to int', 'Returns string representation', 'Compares objects', 'Deletes object'],
      correct: 1,
      explanation: '__str__ returns a human-readable string representation of the object.',
      difficulty: 'hard',
    },
    {
      id: 'cl-8',
      question: 'What is __repr__ used for?',
      options: ['User display', 'Developer/debug representation', 'Comparisons', 'Iteration'],
      correct: 1,
      explanation: '__repr__ returns an unambiguous representation, often for debugging.',
      difficulty: 'hard',
    },
  ],

  'Objects': [
    {
      id: 'ob-1',
      question: 'What is an object?',
      options: ['A class definition', 'An instance of a class', 'A function', 'A module'],
      correct: 1,
      explanation: 'An object is a specific instance created from a class.',
      difficulty: 'easy',
    },
    {
      id: 'ob-2',
      question: 'How do you access an object\'s attribute?',
      options: ['object->attribute', 'object.attribute', 'object[attribute]', 'object::attribute'],
      correct: 1,
      explanation: 'Use dot notation: object.attribute',
      difficulty: 'easy',
    },
    {
      id: 'ob-3',
      question: 'What is isinstance(obj, Class) used for?',
      options: ['Create instance', 'Check if obj is instance of Class', 'Compare objects', 'Copy object'],
      correct: 1,
      explanation: 'isinstance() checks if an object is an instance of a class.',
      difficulty: 'medium',
    },
    {
      id: 'ob-4',
      question: 'What does type(obj) return?',
      options: ['Object value', 'Object\'s class', 'Object ID', 'Object size'],
      correct: 1,
      explanation: 'type() returns the class/type of an object.',
      difficulty: 'easy',
    },
    {
      id: 'ob-5',
      question: 'What is id(obj)?',
      options: ['Object name', 'Object type', 'Object\'s memory address', 'Object hash'],
      correct: 2,
      explanation: 'id() returns a unique identifier (memory address) for an object.',
      difficulty: 'medium',
    },
    {
      id: 'ob-6',
      question: 'How do you check if two variables reference the same object?',
      options: ['a == b', 'a is b', 'a.equals(b)', 'id(a, b)'],
      correct: 1,
      explanation: '"is" checks identity (same object), "==" checks equality (same value).',
      difficulty: 'medium',
    },
    {
      id: 'ob-7',
      question: 'What is hasattr(obj, "name") used for?',
      options: ['Get attribute', 'Check if attribute exists', 'Set attribute', 'Delete attribute'],
      correct: 1,
      explanation: 'hasattr() returns True if the object has the named attribute.',
      difficulty: 'hard',
    },
    {
      id: 'ob-8',
      question: 'What is getattr(obj, "name", default)?',
      options: ['Sets attribute', 'Gets attribute with fallback', 'Deletes attribute', 'Checks attribute'],
      correct: 1,
      explanation: 'getattr() gets an attribute value, returning default if not found.',
      difficulty: 'hard',
    },
  ],

  'Methods': [
    {
      id: 'me-1',
      question: 'What is a method?',
      options: ['A variable', 'A function defined in a class', 'A class', 'A module'],
      correct: 1,
      explanation: 'Methods are functions defined inside a class.',
      difficulty: 'easy',
    },
    {
      id: 'me-2',
      question: 'What is the purpose of self in methods?',
      options: ['Create new instance', 'Reference the current instance', 'Call parent class', 'Define variable'],
      correct: 1,
      explanation: 'self refers to the instance the method is called on.',
      difficulty: 'easy',
    },
    {
      id: 'me-3',
      question: 'What decorator creates a class method?',
      options: ['@staticmethod', '@classmethod', '@method', '@class'],
      correct: 1,
      explanation: '@classmethod creates a method that receives the class as first argument.',
      difficulty: 'medium',
    },
    {
      id: 'me-4',
      question: 'What is a static method?',
      options: ['Method with self', 'Method with cls', 'Method without self or cls', 'Private method'],
      correct: 2,
      explanation: 'Static methods don\'t receive self or cls, like regular functions.',
      difficulty: 'medium',
    },
    {
      id: 'me-5',
      question: 'What is the first parameter of a classmethod?',
      options: ['self', 'cls', 'this', 'class'],
      correct: 1,
      explanation: 'By convention, class methods use "cls" to receive the class.',
      difficulty: 'medium',
    },
    {
      id: 'me-6',
      question: 'When would you use @staticmethod?',
      options: ['When accessing instance data', 'When not accessing instance/class data', 'Always', 'Never'],
      correct: 1,
      explanation: 'Use static methods for utility functions that don\'t need instance or class data.',
      difficulty: 'hard',
    },
    {
      id: 'me-7',
      question: 'What is a property?',
      options: ['A variable', 'A method that looks like an attribute', 'A class', 'A decorator'],
      correct: 1,
      explanation: '@property lets you access a method as if it were an attribute.',
      difficulty: 'hard',
    },
    {
      id: 'me-8',
      question: 'What does @property.setter do?',
      options: ['Get value', 'Set value', 'Delete value', 'Check value'],
      correct: 1,
      explanation: '@property.setter defines how to set a property value.',
      difficulty: 'hard',
    },
  ],

  'Inheritance': [
    {
      id: 'in-1',
      question: 'How do you inherit from a parent class?',
      options: ['class Child extends Parent:', 'class Child(Parent):', 'class Child: Parent', 'class Child inherits Parent:'],
      correct: 1,
      explanation: 'Put the parent class in parentheses: class Child(Parent):',
      difficulty: 'easy',
    },
    {
      id: 'in-2',
      question: 'What does a child class inherit?',
      options: ['Nothing', 'Only methods', 'Only attributes', 'Methods and attributes'],
      correct: 3,
      explanation: 'Child classes inherit both methods and attributes from the parent.',
      difficulty: 'easy',
    },
    {
      id: 'in-3',
      question: 'How do you call the parent\'s __init__?',
      options: ['parent.__init__()', 'super().__init__()', 'this.__init__()', 'base.__init__()'],
      correct: 1,
      explanation: 'super() returns a proxy to the parent class.',
      difficulty: 'medium',
    },
    {
      id: 'in-4',
      question: 'What is method overriding?',
      options: ['Deleting a method', 'Redefining a parent method in child', 'Calling parent method', 'Adding new method'],
      correct: 1,
      explanation: 'Overriding means redefining an inherited method in the child class.',
      difficulty: 'medium',
    },
    {
      id: 'in-5',
      question: 'Can Python classes have multiple parents?',
      options: ['No', 'Yes', 'Only 2', 'Only with special syntax'],
      correct: 1,
      explanation: 'Python supports multiple inheritance: class C(A, B):',
      difficulty: 'medium',
    },
    {
      id: 'in-6',
      question: 'What is the MRO?',
      options: ['Method Return Order', 'Method Resolution Order', 'Multiple Reference Object', 'Main Root Object'],
      correct: 1,
      explanation: 'MRO determines the order in which parent classes are searched for methods.',
      difficulty: 'hard',
    },
    {
      id: 'in-7',
      question: 'What does issubclass(Child, Parent) check?',
      options: ['If Child is instance of Parent', 'If Child inherits from Parent', 'If they are equal', 'If Parent inherits Child'],
      correct: 1,
      explanation: 'issubclass() checks if a class is derived from another class.',
      difficulty: 'hard',
    },
    {
      id: 'in-8',
      question: 'What is the diamond problem?',
      options: ['Syntax error', 'Ambiguity in multiple inheritance', 'Memory issue', 'Import error'],
      correct: 1,
      explanation: 'Diamond problem occurs when a class inherits from two classes that share a common ancestor.',
      difficulty: 'hard',
    },
  ],

  'Polymorphism': [
    {
      id: 'po-1',
      question: 'What is polymorphism?',
      options: ['One class', 'Many forms/behaviors', 'Inheritance', 'Encapsulation'],
      correct: 1,
      explanation: 'Polymorphism means "many forms" - objects of different types responding to same interface.',
      difficulty: 'easy',
    },
    {
      id: 'po-2',
      question: 'What is duck typing?',
      options: ['A Python library', 'If it walks like a duck, treat it like a duck', 'A data type', 'An error'],
      correct: 1,
      explanation: 'Duck typing focuses on what an object can do, not what type it is.',
      difficulty: 'medium',
    },
    {
      id: 'po-3',
      question: 'Which demonstrates polymorphism?',
      options: ['Different classes with same method name', 'Private methods', 'Class attributes', 'Import statements'],
      correct: 0,
      explanation: 'Different classes implementing methods with the same name is polymorphism.',
      difficulty: 'easy',
    },
    {
      id: 'po-4',
      question: 'What is method overloading in Python?',
      options: ['Defining same method multiple times', 'Not natively supported', 'Using decorators', 'Same as overriding'],
      correct: 1,
      explanation: 'Python doesn\'t support traditional overloading. Use default args or *args instead.',
      difficulty: 'medium',
    },
    {
      id: 'po-5',
      question: 'What is an abstract method?',
      options: ['A private method', 'A method without implementation', 'A static method', 'A class method'],
      correct: 1,
      explanation: 'Abstract methods have no implementation and must be overridden in subclasses.',
      difficulty: 'medium',
    },
    {
      id: 'po-6',
      question: 'Which module provides abstract base classes?',
      options: ['abstract', 'abc', 'base', 'interface'],
      correct: 1,
      explanation: 'The abc (Abstract Base Classes) module provides tools for creating abstract classes.',
      difficulty: 'hard',
    },
    {
      id: 'po-7',
      question: 'What decorator marks a method as abstract?',
      options: ['@abstract', '@abstractmethod', '@virtual', '@interface'],
      correct: 1,
      explanation: '@abstractmethod from the abc module marks methods as abstract.',
      difficulty: 'hard',
    },
    {
      id: 'po-8',
      question: 'Can you instantiate an abstract class?',
      options: ['Yes', 'No', 'Only with super()', 'Only if empty'],
      correct: 1,
      explanation: 'Abstract classes cannot be instantiated directly - they must be subclassed.',
      difficulty: 'hard',
    },
  ],

  // ==================== FILES ====================

  'Reading Files': [
    {
      id: 'rf-1',
      question: 'Which function opens a file?',
      options: ['file()', 'open()', 'read()', 'load()'],
      correct: 1,
      explanation: 'The open() function opens a file and returns a file object.',
      difficulty: 'easy',
    },
    {
      id: 'rf-2',
      question: 'What mode opens a file for reading?',
      options: ['"w"', '"r"', '"a"', '"x"'],
      correct: 1,
      explanation: '"r" is read mode. It\'s also the default if no mode is specified.',
      difficulty: 'easy',
    },
    {
      id: 'rf-3',
      question: 'What does file.read() return?',
      options: ['First line', 'All content as string', 'List of lines', 'File object'],
      correct: 1,
      explanation: 'read() returns the entire file content as a single string.',
      difficulty: 'easy',
    },
    {
      id: 'rf-4',
      question: 'What does file.readlines() return?',
      options: ['Single string', 'First line', 'List of lines', 'File size'],
      correct: 2,
      explanation: 'readlines() returns a list where each element is a line from the file.',
      difficulty: 'medium',
    },
    {
      id: 'rf-5',
      question: 'What does file.readline() return?',
      options: ['All lines', 'One line', 'List of words', 'File path'],
      correct: 1,
      explanation: 'readline() reads and returns one line at a time.',
      difficulty: 'medium',
    },
    {
      id: 'rf-6',
      question: 'Why use "with open()" instead of just "open()"?',
      options: ['Faster', 'Automatically closes file', 'More features', 'Required syntax'],
      correct: 1,
      explanation: '"with" ensures the file is properly closed even if an error occurs.',
      difficulty: 'medium',
    },
    {
      id: 'rf-7',
      question: 'How do you read a file line by line efficiently?',
      options: ['readlines()', 'read().split()', 'for line in file:', 'readline() loop'],
      correct: 2,
      explanation: 'Iterating directly over the file object is memory-efficient.',
      difficulty: 'hard',
    },
    {
      id: 'rf-8',
      question: 'What encoding should you specify for text files?',
      options: ['binary', 'utf-8', 'ascii', 'none'],
      correct: 1,
      explanation: 'utf-8 is the recommended encoding for text files.',
      difficulty: 'hard',
    },
  ],

  'Writing Files': [
    {
      id: 'wf-1',
      question: 'What mode opens a file for writing (overwrites)?',
      options: ['"r"', '"w"', '"a"', '"r+"'],
      correct: 1,
      explanation: '"w" mode opens for writing and overwrites existing content.',
      difficulty: 'easy',
    },
    {
      id: 'wf-2',
      question: 'What mode appends to a file?',
      options: ['"w"', '"r"', '"a"', '"x"'],
      correct: 2,
      explanation: '"a" mode appends to the end of the file without overwriting.',
      difficulty: 'easy',
    },
    {
      id: 'wf-3',
      question: 'What does file.write() return?',
      options: ['None', 'The string written', 'Number of characters written', 'True/False'],
      correct: 2,
      explanation: 'write() returns the number of characters written.',
      difficulty: 'medium',
    },
    {
      id: 'wf-4',
      question: 'How do you write multiple lines at once?',
      options: ['write(list)', 'writelines(list)', 'writeall(list)', 'multiwrite(list)'],
      correct: 1,
      explanation: 'writelines() writes a list of strings to the file.',
      difficulty: 'medium',
    },
    {
      id: 'wf-5',
      question: 'Does writelines() add newlines between strings?',
      options: ['Yes', 'No', 'Optional parameter', 'Depends on OS'],
      correct: 1,
      explanation: 'writelines() does NOT add newlines. You must include them in the strings.',
      difficulty: 'medium',
    },
    {
      id: 'wf-6',
      question: 'What does "x" mode do?',
      options: ['Exclusive create (fails if exists)', 'Execute file', 'Extended write', 'Delete file'],
      correct: 0,
      explanation: '"x" creates a new file and fails if it already exists.',
      difficulty: 'hard',
    },
    {
      id: 'wf-7',
      question: 'How do you write and read the same file?',
      options: ['"wr"', '"rw"', '"r+"', '"w+"'],
      correct: 2,
      explanation: '"r+" opens for both reading and writing without truncating.',
      difficulty: 'hard',
    },
    {
      id: 'wf-8',
      question: 'What does file.flush() do?',
      options: ['Deletes content', 'Forces write to disk', 'Closes file', 'Clears buffer'],
      correct: 1,
      explanation: 'flush() forces any buffered data to be written to the file.',
      difficulty: 'hard',
    },
  ],

  'File Context': [
    {
      id: 'fc-1',
      question: 'What is a context manager?',
      options: ['File reader', 'Object managing resources with "with"', 'Error handler', 'Memory manager'],
      correct: 1,
      explanation: 'Context managers handle setup and cleanup of resources automatically.',
      difficulty: 'easy',
    },
    {
      id: 'fc-2',
      question: 'What methods must a context manager implement?',
      options: ['start() and stop()', '__enter__ and __exit__', 'open() and close()', 'init() and del()'],
      correct: 1,
      explanation: '__enter__ runs on entry, __exit__ runs on exit (cleanup).',
      difficulty: 'medium',
    },
    {
      id: 'fc-3',
      question: 'When does __exit__ run?',
      options: ['On entry', 'After with block (always)', 'Only on error', 'Never'],
      correct: 1,
      explanation: '__exit__ always runs when leaving the with block, even on errors.',
      difficulty: 'medium',
    },
    {
      id: 'fc-4',
      question: 'What does "as" do in: with open("f") as file:?',
      options: ['Renames file', 'Assigns __enter__ return value', 'Checks type', 'Creates alias'],
      correct: 1,
      explanation: '"as" assigns the return value of __enter__ to a variable.',
      difficulty: 'medium',
    },
    {
      id: 'fc-5',
      question: 'Can you open multiple files in one with statement?',
      options: ['No', 'Yes', 'Only 2', 'Only same type'],
      correct: 1,
      explanation: 'Yes: with open("a") as f1, open("b") as f2:',
      difficulty: 'hard',
    },
    {
      id: 'fc-6',
      question: 'What decorator creates a context manager from a generator?',
      options: ['@contextlib.contextmanager', '@with', '@context', '@manager'],
      correct: 0,
      explanation: '@contextmanager from contextlib turns a generator into a context manager.',
      difficulty: 'hard',
    },
    {
      id: 'fc-7',
      question: 'What happens if __exit__ returns True?',
      options: ['Error is raised', 'Exception is suppressed', 'File is deleted', 'Nothing special'],
      correct: 1,
      explanation: 'Returning True from __exit__ suppresses any exception that occurred.',
      difficulty: 'hard',
    },
    {
      id: 'fc-8',
      question: 'What are the __exit__ parameters?',
      options: ['None', 'error', 'exc_type, exc_val, exc_tb', 'file, mode'],
      correct: 2,
      explanation: '__exit__ receives exception type, value, and traceback (or None if no error).',
      difficulty: 'hard',
    },
  ],

  'JSON & CSV': [
    {
      id: 'jc-1',
      question: 'Which module handles JSON in Python?',
      options: ['js', 'json', 'javascript', 'serialize'],
      correct: 1,
      explanation: 'The json module provides JSON encoding and decoding.',
      difficulty: 'easy',
    },
    {
      id: 'jc-2',
      question: 'What does json.loads() do?',
      options: ['Loads file', 'Parses JSON string', 'Writes JSON', 'Validates JSON'],
      correct: 1,
      explanation: 'loads() (load string) parses a JSON string into Python objects.',
      difficulty: 'easy',
    },
    {
      id: 'jc-3',
      question: 'What does json.dumps() do?',
      options: ['Reads file', 'Parses string', 'Converts Python to JSON string', 'Deletes JSON'],
      correct: 2,
      explanation: 'dumps() (dump string) converts Python objects to a JSON string.',
      difficulty: 'easy',
    },
    {
      id: 'jc-4',
      question: 'Which module handles CSV files?',
      options: ['comma', 'csv', 'table', 'excel'],
      correct: 1,
      explanation: 'The csv module provides tools for reading and writing CSV files.',
      difficulty: 'easy',
    },
    {
      id: 'jc-5',
      question: 'What is csv.reader() used for?',
      options: ['Writing CSV', 'Reading CSV rows', 'Parsing JSON', 'Creating headers'],
      correct: 1,
      explanation: 'csv.reader() creates an iterator over CSV rows.',
      difficulty: 'medium',
    },
    {
      id: 'jc-6',
      question: 'What does json.load() (without s) do?',
      options: ['Parses string', 'Reads from file', 'Writes to file', 'Same as loads'],
      correct: 1,
      explanation: 'load() reads JSON directly from a file object.',
      difficulty: 'medium',
    },
    {
      id: 'jc-7',
      question: 'How do you pretty-print JSON?',
      options: ['json.pretty()', 'json.dumps(indent=2)', 'json.format()', 'print(json)'],
      correct: 1,
      explanation: 'The indent parameter in dumps() adds indentation for readability.',
      difficulty: 'hard',
    },
    {
      id: 'jc-8',
      question: 'What does csv.DictReader do?',
      options: ['Reads as lists', 'Reads rows as dictionaries', 'Writes dicts', 'Reads JSON'],
      correct: 1,
      explanation: 'DictReader reads CSV rows as dictionaries with headers as keys.',
      difficulty: 'hard',
    },
  ],

  // ==================== ERRORS ====================

  'Try/Except': [
    {
      id: 'te-1',
      question: 'What keyword starts error handling?',
      options: ['catch', 'handle', 'try', 'error'],
      correct: 2,
      explanation: '"try" starts a block that might raise an exception.',
      difficulty: 'easy',
    },
    {
      id: 'te-2',
      question: 'What keyword catches an exception?',
      options: ['catch', 'except', 'handle', 'error'],
      correct: 1,
      explanation: '"except" catches and handles exceptions.',
      difficulty: 'easy',
    },
    {
      id: 'te-3',
      question: 'What does the finally block do?',
      options: ['Catches errors', 'Always runs (cleanup)', 'Raises errors', 'Ignores errors'],
      correct: 1,
      explanation: '"finally" always executes, whether an exception occurred or not.',
      difficulty: 'easy',
    },
    {
      id: 'te-4',
      question: 'How do you catch a specific exception type?',
      options: ['except Error:', 'except(TypeError):', 'except TypeError:', 'catch TypeError:'],
      correct: 2,
      explanation: 'Specify the exception type after except: except TypeError:',
      difficulty: 'medium',
    },
    {
      id: 'te-5',
      question: 'How do you catch multiple exception types?',
      options: ['except E1, E2:', 'except (E1, E2):', 'except E1 or E2:', 'except E1 | E2:'],
      correct: 1,
      explanation: 'Use a tuple: except (TypeError, ValueError):',
      difficulty: 'medium',
    },
    {
      id: 'te-6',
      question: 'How do you access the exception object?',
      options: ['except Error:', 'except Error as e:', 'except e = Error:', 'except (e) Error:'],
      correct: 1,
      explanation: 'Use "as" to bind the exception: except Error as e:',
      difficulty: 'medium',
    },
    {
      id: 'te-7',
      question: 'What does "else" do in try/except?',
      options: ['Catches all errors', 'Runs if no exception', 'Same as finally', 'Raises error'],
      correct: 1,
      explanation: '"else" runs only if no exception was raised in the try block.',
      difficulty: 'hard',
    },
    {
      id: 'te-8',
      question: 'What is the order of: try, except, else, finally?',
      options: ['Any order', 'try-except-else-finally', 'try-else-except-finally', 'try-finally-except-else'],
      correct: 1,
      explanation: 'The order must be: try, then except, then else, then finally.',
      difficulty: 'hard',
    },
  ],

  'Exception Types': [
    {
      id: 'et-1',
      question: 'What exception is raised by 1/0?',
      options: ['DivisionError', 'ZeroDivisionError', 'MathError', 'ValueError'],
      correct: 1,
      explanation: 'Division by zero raises ZeroDivisionError.',
      difficulty: 'easy',
    },
    {
      id: 'et-2',
      question: 'What exception is raised by int("abc")?',
      options: ['TypeError', 'ValueError', 'ConversionError', 'IntError'],
      correct: 1,
      explanation: 'Invalid literal for int() raises ValueError.',
      difficulty: 'easy',
    },
    {
      id: 'et-3',
      question: 'What exception is raised by accessing undefined variable?',
      options: ['ValueError', 'TypeError', 'NameError', 'ReferenceError'],
      correct: 2,
      explanation: 'Undefined variable names raise NameError.',
      difficulty: 'easy',
    },
    {
      id: 'et-4',
      question: 'What exception is raised by list[999] on a small list?',
      options: ['ValueError', 'IndexError', 'KeyError', 'RangeError'],
      correct: 1,
      explanation: 'Accessing an invalid list index raises IndexError.',
      difficulty: 'medium',
    },
    {
      id: 'et-5',
      question: 'What exception is raised by dict["missing_key"]?',
      options: ['IndexError', 'ValueError', 'KeyError', 'LookupError'],
      correct: 2,
      explanation: 'Accessing a missing dictionary key raises KeyError.',
      difficulty: 'medium',
    },
    {
      id: 'et-6',
      question: 'What exception is raised by "a" + 1?',
      options: ['ValueError', 'TypeError', 'AddError', 'StringError'],
      correct: 1,
      explanation: 'Incompatible types in operations raise TypeError.',
      difficulty: 'medium',
    },
    {
      id: 'et-7',
      question: 'What is the base class for all exceptions?',
      options: ['Error', 'Exception', 'BaseException', 'Throwable'],
      correct: 2,
      explanation: 'BaseException is the root of all exceptions. Exception is for most errors.',
      difficulty: 'hard',
    },
    {
      id: 'et-8',
      question: 'What exception is raised when import fails?',
      options: ['ImportError', 'ModuleError', 'LoadError', 'PackageError'],
      correct: 0,
      explanation: 'Failed imports raise ImportError (or ModuleNotFoundError in Python 3.6+).',
      difficulty: 'hard',
    },
  ],

  'Raising Exceptions': [
    {
      id: 're-1',
      question: 'Which keyword raises an exception?',
      options: ['throw', 'raise', 'error', 'except'],
      correct: 1,
      explanation: '"raise" is used to raise exceptions in Python.',
      difficulty: 'easy',
    },
    {
      id: 're-2',
      question: 'How do you raise a ValueError with a message?',
      options: ['raise ValueError, "msg"', 'raise ValueError("msg")', 'raise "msg" ValueError', 'throw ValueError("msg")'],
      correct: 1,
      explanation: 'raise ExceptionType("message") raises with a message.',
      difficulty: 'easy',
    },
    {
      id: 're-3',
      question: 'Can you re-raise the current exception?',
      options: ['No', 'Yes, with "raise"', 'Yes, with "throw"', 'Only in finally'],
      correct: 1,
      explanation: 'Just "raise" in an except block re-raises the current exception.',
      difficulty: 'medium',
    },
    {
      id: 're-4',
      question: 'What does "raise from" do?',
      options: ['Imports exception', 'Creates exception chain', 'Raises multiple', 'Catches exception'],
      correct: 1,
      explanation: '"raise X from Y" chains exceptions, showing Y caused X.',
      difficulty: 'medium',
    },
    {
      id: 're-5',
      question: 'When should you raise an exception?',
      options: ['Never', 'When error recovery impossible', 'Always', 'Only in main()'],
      correct: 1,
      explanation: 'Raise exceptions for errors that the current code cannot handle.',
      difficulty: 'medium',
    },
    {
      id: 're-6',
      question: 'What is "raise from None"?',
      options: ['Invalid syntax', 'Suppresses exception chain', 'Raises None', 'Clears all errors'],
      correct: 1,
      explanation: '"raise X from None" hides the original exception that caused X.',
      difficulty: 'hard',
    },
    {
      id: 're-7',
      question: 'Can you raise a string as an exception?',
      options: ['Yes', 'No', 'Only in Python 2', 'With special syntax'],
      correct: 1,
      explanation: 'Only BaseException subclasses can be raised.',
      difficulty: 'hard',
    },
    {
      id: 're-8',
      question: 'What is an assertion?',
      options: ['A type of loop', 'Debug check that raises AssertionError', 'Exception handler', 'Variable declaration'],
      correct: 1,
      explanation: '"assert condition" raises AssertionError if condition is False.',
      difficulty: 'hard',
    },
  ],

  'Custom Exceptions': [
    {
      id: 'ce-1',
      question: 'What class should custom exceptions inherit from?',
      options: ['Object', 'Error', 'Exception', 'BaseError'],
      correct: 2,
      explanation: 'Custom exceptions should inherit from Exception or a subclass.',
      difficulty: 'easy',
    },
    {
      id: 'ce-2',
      question: 'What is the simplest custom exception?',
      options: ['class MyError: pass', 'class MyError(Exception): pass', 'def MyError(): pass', 'exception MyError: pass'],
      correct: 1,
      explanation: 'Inherit from Exception with pass for minimal implementation.',
      difficulty: 'easy',
    },
    {
      id: 'ce-3',
      question: 'Why create custom exceptions?',
      options: ['Required by Python', 'More specific error handling', 'Faster execution', 'Smaller code'],
      correct: 1,
      explanation: 'Custom exceptions allow catching specific error types for your application.',
      difficulty: 'medium',
    },
    {
      id: 'ce-4',
      question: 'How do you add a custom message to your exception?',
      options: ['message attribute', 'Override __init__', '__str__ only', 'msg parameter'],
      correct: 1,
      explanation: 'Override __init__ to accept and store custom messages.',
      difficulty: 'medium',
    },
    {
      id: 'ce-5',
      question: 'Can custom exceptions have multiple attributes?',
      options: ['No', 'Yes', 'Only one', 'Only strings'],
      correct: 1,
      explanation: 'Custom exceptions can have any attributes you need.',
      difficulty: 'medium',
    },
    {
      id: 'ce-6',
      question: 'What naming convention is used for exceptions?',
      options: ['lowercase', 'UPPERCASE', 'PascalCase with Error suffix', 'snake_case'],
      correct: 2,
      explanation: 'Exception names use PascalCase and often end with "Error".',
      difficulty: 'hard',
    },
    {
      id: 'ce-7',
      question: 'Should you inherit from BaseException?',
      options: ['Yes, always', 'No, use Exception', 'Only for critical errors', 'Makes no difference'],
      correct: 1,
      explanation: 'BaseException includes SystemExit, KeyboardInterrupt. Use Exception for application errors.',
      difficulty: 'hard',
    },
    {
      id: 'ce-8',
      question: 'How do you create an exception hierarchy?',
      options: ['Cannot be done', 'Inherit from your base exception', 'Use decorators', 'Use metaclasses'],
      correct: 1,
      explanation: 'Create a base exception, then inherit specific exceptions from it.',
      difficulty: 'hard',
    },
  ],

  // ==================== LIBRARIES ====================

  'Import Statements': [
    {
      id: 'is-1',
      question: 'How do you import the math module?',
      options: ['include math', 'import math', 'using math', 'require math'],
      correct: 1,
      explanation: '"import module_name" imports a module.',
      difficulty: 'easy',
    },
    {
      id: 'is-2',
      question: 'How do you import just the sqrt function from math?',
      options: ['import sqrt from math', 'from math import sqrt', 'import math.sqrt', 'math import sqrt'],
      correct: 1,
      explanation: '"from module import name" imports specific items.',
      difficulty: 'easy',
    },
    {
      id: 'is-3',
      question: 'How do you import with an alias?',
      options: ['import numpy = np', 'import numpy as np', 'import numpy -> np', 'alias numpy np'],
      correct: 1,
      explanation: '"import module as alias" creates a shorter name.',
      difficulty: 'easy',
    },
    {
      id: 'is-4',
      question: 'What does "from math import *" do?',
      options: ['Imports math object', 'Imports all public names', 'Imports first item', 'Syntax error'],
      correct: 1,
      explanation: '* imports all public names (not recommended in production code).',
      difficulty: 'medium',
    },
    {
      id: 'is-5',
      question: 'Where should import statements be placed?',
      options: ['Anywhere', 'Top of the file', 'End of file', 'Inside functions'],
      correct: 1,
      explanation: 'By convention, imports go at the top of the file.',
      difficulty: 'medium',
    },
    {
      id: 'is-6',
      question: 'What is a relative import?',
      options: ['Importing from parent package', 'Importing by full path', 'Same as regular import', 'Importing from web'],
      correct: 0,
      explanation: 'Relative imports use . or .. to import from the current or parent package.',
      difficulty: 'hard',
    },
    {
      id: 'is-7',
      question: 'What is __all__ used for?',
      options: ['Import everything', 'Define public API for * imports', 'Check imports', 'List modules'],
      correct: 1,
      explanation: '__all__ lists names exported when using "from module import *".',
      difficulty: 'hard',
    },
    {
      id: 'is-8',
      question: 'What does "if __name__ == \'__main__\':" check?',
      options: ['If file exists', 'If run directly vs imported', 'If function is main', 'If name is valid'],
      correct: 1,
      explanation: 'This checks if the file is run directly (not imported).',
      difficulty: 'hard',
    },
  ],

  'Standard Library': [
    {
      id: 'sl-1',
      question: 'Which module provides random number functions?',
      options: ['rand', 'random', 'rng', 'numbers'],
      correct: 1,
      explanation: 'The random module provides random number generation.',
      difficulty: 'easy',
    },
    {
      id: 'sl-2',
      question: 'Which module provides date and time functions?',
      options: ['time', 'datetime', 'date', 'Both A and B'],
      correct: 3,
      explanation: 'Both time and datetime modules handle date/time operations.',
      difficulty: 'easy',
    },
    {
      id: 'sl-3',
      question: 'Which module provides OS-related functions?',
      options: ['system', 'os', 'platform', 'shell'],
      correct: 1,
      explanation: 'The os module provides operating system interfaces.',
      difficulty: 'easy',
    },
    {
      id: 'sl-4',
      question: 'What does the re module provide?',
      options: ['Recursion', 'Regular expressions', 'References', 'Rendering'],
      correct: 1,
      explanation: 're provides regular expression matching operations.',
      difficulty: 'medium',
    },
    {
      id: 'sl-5',
      question: 'Which module handles file paths cross-platform?',
      options: ['path', 'os.path', 'filepath', 'pathlib'],
      correct: 3,
      explanation: 'pathlib (modern) and os.path both handle paths cross-platform.',
      difficulty: 'medium',
    },
    {
      id: 'sl-6',
      question: 'What does collections module provide?',
      options: ['Garbage collection', 'Specialized data structures', 'Data collection', 'List operations'],
      correct: 1,
      explanation: 'collections provides specialized container datatypes like Counter, deque.',
      difficulty: 'medium',
    },
    {
      id: 'sl-7',
      question: 'Which module helps with function tools?',
      options: ['funcs', 'functools', 'tools', 'utilities'],
      correct: 1,
      explanation: 'functools provides higher-order functions like reduce, lru_cache.',
      difficulty: 'hard',
    },
    {
      id: 'sl-8',
      question: 'What does itertools module provide?',
      options: ['Loop utilities', 'Iterator building blocks', 'List tools', 'Index tools'],
      correct: 1,
      explanation: 'itertools provides efficient iterators for looping.',
      difficulty: 'hard',
    },
  ],

  'pip & packages': [
    {
      id: 'pp-1',
      question: 'What is pip?',
      options: ['Python IDE', 'Package installer', 'Python interpreter', 'Programming interface'],
      correct: 1,
      explanation: 'pip is the package installer for Python.',
      difficulty: 'easy',
    },
    {
      id: 'pp-2',
      question: 'How do you install a package with pip?',
      options: ['pip get package', 'pip install package', 'pip add package', 'pip download package'],
      correct: 1,
      explanation: '"pip install package_name" installs a package.',
      difficulty: 'easy',
    },
    {
      id: 'pp-3',
      question: 'How do you list installed packages?',
      options: ['pip show', 'pip list', 'pip packages', 'pip installed'],
      correct: 1,
      explanation: '"pip list" shows all installed packages.',
      difficulty: 'easy',
    },
    {
      id: 'pp-4',
      question: 'How do you uninstall a package?',
      options: ['pip remove', 'pip delete', 'pip uninstall', 'pip drop'],
      correct: 2,
      explanation: '"pip uninstall package_name" removes a package.',
      difficulty: 'medium',
    },
    {
      id: 'pp-5',
      question: 'What file lists project dependencies?',
      options: ['packages.txt', 'requirements.txt', 'dependencies.txt', 'pip.txt'],
      correct: 1,
      explanation: 'requirements.txt is the standard file for listing dependencies.',
      difficulty: 'medium',
    },
    {
      id: 'pp-6',
      question: 'How do you install from requirements.txt?',
      options: ['pip install requirements.txt', 'pip install -r requirements.txt', 'pip requirements.txt', 'pip load requirements.txt'],
      correct: 1,
      explanation: '-r flag reads requirements from a file.',
      difficulty: 'medium',
    },
    {
      id: 'pp-7',
      question: 'How do you install a specific version?',
      options: ['pip install pkg@1.0', 'pip install pkg==1.0', 'pip install pkg:1.0', 'pip install pkg-1.0'],
      correct: 1,
      explanation: 'Use == to specify an exact version: pip install package==1.0',
      difficulty: 'hard',
    },
    {
      id: 'pp-8',
      question: 'What is PyPI?',
      options: ['Python IDE', 'Package repository', 'Python interpreter', 'Programming interface'],
      correct: 1,
      explanation: 'PyPI (Python Package Index) is the official package repository.',
      difficulty: 'hard',
    },
  ],

  'Virtual Environments': [
    {
      id: 've-1',
      question: 'What is a virtual environment?',
      options: ['Cloud Python', 'Isolated Python installation', 'Python IDE', 'Container'],
      correct: 1,
      explanation: 'Virtual environments isolate project dependencies from system Python.',
      difficulty: 'easy',
    },
    {
      id: 've-2',
      question: 'How do you create a virtual environment?',
      options: ['python venv create', 'python -m venv envname', 'venv create envname', 'pip venv envname'],
      correct: 1,
      explanation: '"python -m venv envname" creates a new virtual environment.',
      difficulty: 'easy',
    },
    {
      id: 've-3',
      question: 'Why use virtual environments?',
      options: ['Faster code', 'Isolated dependencies', 'Better debugging', 'Required by Python'],
      correct: 1,
      explanation: 'Virtual environments prevent dependency conflicts between projects.',
      difficulty: 'easy',
    },
    {
      id: 've-4',
      question: 'How do you activate a venv on Windows?',
      options: ['source venv/bin/activate', 'venv\\Scripts\\activate', 'activate venv', './venv/activate'],
      correct: 1,
      explanation: 'On Windows, run venv\\Scripts\\activate.',
      difficulty: 'medium',
    },
    {
      id: 've-5',
      question: 'How do you activate a venv on Linux/Mac?',
      options: ['venv\\Scripts\\activate', 'source venv/bin/activate', 'activate venv', './venv/activate'],
      correct: 1,
      explanation: 'On Linux/Mac, run source venv/bin/activate.',
      difficulty: 'medium',
    },
    {
      id: 've-6',
      question: 'How do you deactivate a virtual environment?',
      options: ['exit', 'deactivate', 'quit', 'stop'],
      correct: 1,
      explanation: 'Simply type "deactivate" to exit the virtual environment.',
      difficulty: 'medium',
    },
    {
      id: 've-7',
      question: 'What should NOT be committed to version control?',
      options: ['requirements.txt', 'venv folder', 'Python files', 'Config files'],
      correct: 1,
      explanation: 'The venv folder should be gitignored. Use requirements.txt instead.',
      difficulty: 'hard',
    },
    {
      id: 've-8',
      question: 'What is the difference between venv and virtualenv?',
      options: ['No difference', 'venv is built-in (3.3+), virtualenv is third-party', 'virtualenv is newer', 'venv is faster'],
      correct: 1,
      explanation: 'venv is built into Python 3.3+. virtualenv is a third-party tool with more features.',
      difficulty: 'hard',
    },
  ],
};

/**
 * Get quizzes for a topic
 */
export function getQuizzesForTopic(topicName: string): Quiz[] {
  return TOPIC_QUIZZES[topicName] || [];
}

/**
 * Get all topic names that have quizzes
 */
export function getTopicsWithQuizzes(): string[] {
  return Object.keys(TOPIC_QUIZZES);
}

/**
 * Get quiz count for a topic
 */
export function getQuizCount(topicName: string): number {
  return TOPIC_QUIZZES[topicName]?.length || 0;
}
